<?php

namespace Database\Seeders;

use App\Models\Service;
use App\Models\Media;
use Illuminate\Database\Seeder;
use Illuminate\Support\Str;

class ServiceSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $services = [
            [
                'name' => 'Pembangunan Sistem Web',
                'name_en' => 'Web System Development',
                'description' => 'Sistem web korporat, e-dagang, portal dalaman dan aplikasi web progressif (PWA) yang dibina khas menggunakan teknologi terkini.',
                'description_en' => 'Corporate web systems, e-commerce, internal portals and progressive web apps (PWA) built with the latest technology.',
                'content' => '<p>Kami menyediakan perkhidmatan pembangunan sistem web yang menyeluruh, merangkumi setiap fasa kitaran hayat pembangunan perisian — daripada analisis keperluan, reka bentuk seni bina sistem, pembangunan, pengujian, sehinggalah kepada pelancaran dan penyelenggaraan berterusan. Setiap sistem yang kami bangunkan dibina dengan fokus utama kepada prestasi, keselamatan, dan kebolehskalaan untuk memastikan ia mampu menampung pertumbuhan perniagaan anda pada masa hadapan.</p><p>Kami menggunakan stack teknologi moden seperti Laravel, React, Vue.js, dan Node.js bagi memastikan setiap aplikasi web yang dihasilkan bukan sahaja pantas dan responsif, tetapi juga mudah diselenggara dan dikembangkan. Pendekatan kami menekankan prinsip clean architecture dan reka bentuk modular, membolehkan komponen sistem dikemas kini secara bebas tanpa menjejaskan keseluruhan ekosistem aplikasi.</p><p>Selain itu, kami turut menawarkan integrasi pihak ketiga yang meluas — daripada gerbang pembayaran seperti Stripe, PayPal, dan iPay88, kepada perkhidmatan SMS, emel, sistem CRM, ERP, dan platform analitik data. Setiap integrasi diuji dengan teliti bagi memastikan aliran data yang lancar dan selamat antara sistem-sistem berbeza. Kami juga menyediakan dokumentasi teknikal yang lengkap serta latihan kepada pasukan teknikal anda bagi memudahkan proses pemindahan pengetahuan dan pengurusan sistem secara dalaman.</p><p>Keselamatan merupakan keutamaan kami dalam setiap projek pembangunan. Kami melaksanakan amalan terbaik keselamatan aplikasi web seperti OWASP Top 10, pengesahan berbilang faktor (MFA), penyulitan data end-to-end, perlindungan CSRF dan XSS, serta audit keselamatan berkala. Setiap sistem melalui ujian penembusan (penetration testing) sebelum dilancarkan bagi memastikan tiada kelemahan keselamatan yang boleh dieksploitasi oleh pihak tidak bertanggungjawab.</p>',
                'content_en' => '<p>We provide comprehensive web system development services covering every phase of the software development lifecycle — from requirements analysis, system architecture design, development, testing, to deployment and ongoing maintenance. Every system we build is developed with a primary focus on performance, security, and scalability to ensure it can accommodate your business growth well into the future.</p><p>We leverage modern technology stacks such as Laravel, React, Vue.js, and Node.js to ensure every web application we produce is not only fast and responsive, but also easy to maintain and extend. Our approach emphasizes clean architecture principles and modular design, allowing system components to be updated independently without compromising the entire application ecosystem.</p><p>In addition, we offer extensive third-party integrations — from payment gateways such as Stripe, PayPal, and iPay88, to SMS services, email, CRM systems, ERP platforms, and data analytics tools. Every integration is meticulously tested to guarantee smooth and secure data flow between disparate systems. We also provide comprehensive technical documentation and training for your technical team to facilitate knowledge transfer and internal system management.</p><p>Security is our utmost priority in every development project. We implement web application security best practices such as OWASP Top 10, multi-factor authentication (MFA), end-to-end data encryption, CSRF and XSS protection, and periodic security audits. Every system undergoes penetration testing prior to launch to ensure no security vulnerabilities exist that could be exploited by malicious actors.</p>',
                'features' => ['Laravel & React', 'API Integration', 'Real-time Dashboard', 'Scalable Architecture'],
                'features_en' => ['Laravel & React', 'API Integration', 'Real-time Dashboard', 'Scalable Architecture'],
                'icon' => 'Monitor',
                'bg_path' => 'services/dev_bg.png',
                'order' => 1,
            ],
            [
                'name' => 'Rekabentuk UI/UX',
                'name_en' => 'UI/UX Design',
                'description' => 'Rekabentuk antara muka pengguna yang moden, intuitif dan menarik menggunakan prinsip design thinking.',
                'description_en' => 'Modern, intuitive, and attractive user interfaces using design thinking principles.',
                'content' => '<p>Perkhidmatan reka bentuk UI/UX kami bermula dengan pemahaman mendalam terhadap pengguna sasaran anda. Melalui sesi kajian pengguna (user research), temu bual, dan analisis persona, kami mengenal pasti keperluan sebenar, tingkah laku, dan titik kesakitan (pain points) pengguna. Data-data ini menjadi asas kepada setiap keputusan reka bentuk yang kami buat, memastikan produk akhir bukan sahaja cantik dipandang, tetapi benar-benar berfungsi untuk menyelesaikan masalah pengguna dengan efisien.</p><p>Proses reka bentuk kami mengikuti kerangka Design Thinking yang telah terbukti keberkesanannya: Empathize, Define, Ideate, Prototype, dan Test. Kami menghasilkan wireframe interaktif dan prototaip fidelity tinggi menggunakan alat-alat industri seperti Figma dan Adobe XD. Setiap prototaip diuji dengan pengguna sebenar melalui sesi usability testing, dan maklum balas yang diperoleh digunakan untuk memperhalusi reka bentuk secara berterusan sehingga mencapai tahap kepuasan pengguna yang optimum.</p><p>Kami juga membangunkan Design System yang komprehensif untuk setiap projek — satu set komponen UI yang boleh diguna semula, panduan gaya (style guide), dan dokumentasi yang memastikan konsistensi visual di seluruh platform. Design System ini memudahkan kerjasama antara pereka bentuk dan pembangun, mempercepatkan proses pembangunan, dan memastikan identiti jenama anda kekal konsisten walaupun ketika pasukan berkembang.</p><p>Aksesibiliti (accessibility) juga merupakan fokus penting dalam reka bentuk kami. Kami memastikan setiap antara muka mematuhi piawaian WCAG 2.1 AA, menjadikan aplikasi anda boleh diakses oleh semua pengguna termasuk mereka yang mempunyai ketidakupayaan penglihatan, pendengaran, atau motor. Ini bukan sahaja tanggungjawab sosial, tetapi juga membuka pasaran yang lebih luas untuk produk anda.</p>',
                'content_en' => '<p>Our UI/UX design services begin with a deep understanding of your target users. Through user research sessions, interviews, and persona analysis, we identify real needs, behaviors, and pain points. This data forms the foundation of every design decision we make, ensuring the final product is not only visually appealing but truly functional in solving user problems efficiently.</p><p>Our design process follows the proven Design Thinking framework: Empathize, Define, Ideate, Prototype, and Test. We produce interactive wireframes and high-fidelity prototypes using industry-standard tools such as Figma and Adobe XD. Every prototype is tested with real users through usability testing sessions, and the feedback obtained is used to continuously refine the design until optimal user satisfaction is achieved.</p><p>We also develop a comprehensive Design System for every project — a set of reusable UI components, style guides, and documentation that ensures visual consistency across the entire platform. This Design System facilitates collaboration between designers and developers, accelerates the development process, and ensures your brand identity remains consistent even as your team grows.</p><p>Accessibility is also a key focus in our design approach. We ensure every interface complies with WCAG 2.1 AA standards, making your application accessible to all users including those with visual, auditory, or motor disabilities. This is not only a social responsibility but also opens up a wider market for your product.</p>',
                'features' => ['User Research', 'Wireframing', 'Prototyping', 'Design System'],
                'features_en' => ['User Research', 'Wireframing', 'Prototyping', 'Design System'],
                'icon' => 'Palette',
                'bg_path' => 'services/design_bg.png',
                'order' => 2,
            ],
            [
                'name' => 'Cloud & Hosting',
                'name_en' => 'Cloud & Hosting',
                'description' => 'Infrastruktur awan yang selamat dan berprestasi tinggi untuk aplikasi kritikal perniagaan anda.',
                'description_en' => 'Secure and high-performance cloud infrastructure for your critical business applications.',
                'content' => '<p>Dalam era digital yang menuntut ketersediaan 24/7, infrastruktur awan yang kukuh adalah tulang belakang kepada kejayaan operasi perniagaan moden. Kami menawarkan perkhidmatan cloud dan hosting yang menyeluruh, merangkumi perancangan seni bina awan, migrasi, pengurusan, pengoptimuman kos, dan pemantauan berterusan. Kami bekerjasama rapat dengan penyedia perkhidmatan awan terkemuka seperti Amazon Web Services (AWS), Microsoft Azure, dan Google Cloud Platform (GCP) untuk menawarkan penyelesaian terbaik yang disesuaikan dengan bajet dan keperluan teknikal anda.</p><p>Pendekatan kami terhadap pengurusan infrastruktur adalah berasaskan prinsip Infrastructure as Code (IaC) menggunakan alat seperti Terraform, Ansible, dan CloudFormation. Ini membolehkan setiap konfigurasi infrastruktur direkodkan dalam bentuk kod yang boleh diuji, diaudit, dan direplikasi dengan mudah. Sebarang perubahan infrastruktur melalui proses semakan yang ketat, mengurangkan risiko kesilapan konfigurasi yang boleh menyebabkan gangguan perkhidmatan.</p><p>Kami juga menawarkan penyelesaian containerization dan orkestrasi menggunakan Docker dan Kubernetes. Pendekatan ini membolehkan aplikasi anda dijalankan dalam persekitaran yang terasing, konsisten, dan mudah diskalakan. Dengan konfigurasi auto-scaling yang pintar, sumber pengkomputeran ditambah atau dikurangkan secara automatik berdasarkan beban trafik sebenar, memastikan prestasi optimum pada setiap masa tanpa pembaziran kos.</p><p>Keselamatan data anda adalah keutamaan kami. Kami melaksanakan lapisan keselamatan berganda termasuk firewall aplikasi web (WAF), pengesanan pencerobohan (IDS/IPS), penyulitan data semasa rehat (at rest) dan semasa transit (in transit), pengurusan identiti dan akses (IAM), serta sandaran automatik harian dengan pengekalan sehingga 90 hari. Semua ini dipantau 24/7 oleh pasukan operasi keselamatan kami melalui dashboard pemantauan masa nyata.</p>',
                'content_en' => '<p>In an era demanding 24/7 availability, robust cloud infrastructure is the backbone of modern business operational success. We offer comprehensive cloud and hosting services covering cloud architecture planning, migration, management, cost optimization, and continuous monitoring. We work closely with leading cloud service providers such as Amazon Web Services (AWS), Microsoft Azure, and Google Cloud Platform (GCP) to deliver the best solutions tailored to your budget and technical requirements.</p><p>Our approach to infrastructure management is based on Infrastructure as Code (IaC) principles using tools like Terraform, Ansible, and CloudFormation. This enables every infrastructure configuration to be recorded in code form that can be tested, audited, and easily replicated. Any infrastructure changes undergo a rigorous review process, reducing the risk of misconfigurations that could cause service disruptions.</p><p>We also offer containerization and orchestration solutions using Docker and Kubernetes. This approach allows your applications to run in isolated, consistent, and easily scalable environments. With intelligent auto-scaling configurations, computing resources are automatically added or reduced based on actual traffic loads, ensuring optimal performance at all times without cost wastage.</p><p>Your data security is our priority. We implement multiple layers of security including web application firewalls (WAF), intrusion detection and prevention systems (IDS/IPS), data encryption at rest and in transit, identity and access management (IAM), and automated daily backups with up to 90-day retention. All of this is monitored 24/7 by our security operations team through real-time monitoring dashboards.</p>',
                'features' => ['AWS & Azure', '99.9% Uptime', 'Auto Scaling', 'Daily Backup'],
                'features_en' => ['AWS & Azure', '99.9% Uptime', 'Auto Scaling', 'Daily Backup'],
                'icon' => 'Cloud',
                'bg_path' => 'services/cloud_bg.png',
                'order' => 3,
            ],
            [
                'name' => 'AI & Automasi',
                'name_en' => 'AI & Automation',
                'description' => 'Penyelesaian kecerdasan buatan termasuk chatbot, analitik ramalan dan automasi proses.',
                'description_en' => 'Artificial intelligence solutions including chatbots, predictive analytics and process automation.',
                'content' => '<p>Kecerdasan buatan (AI) dan automasi kini bukan lagi teknologi masa hadapan — ia adalah keperluan semasa untuk organisasi yang ingin kekal kompetitif dalam pasaran yang semakin pantas berubah. Kami menawarkan penyelesaian AI dan automasi yang disesuaikan khas untuk keperluan perniagaan anda, daripada chatbot perkhidmatan pelanggan pintar sehinggalah kepada sistem analitik ramalan yang kompleks untuk membantu membuat keputusan strategik yang lebih tepat dan pantas.</p><p>Pasukan sains data kami mempunyai kepakaran dalam pelbagai bidang AI termasuk Pemprosesan Bahasa Tabii (NLP), Penglihatan Komputer (Computer Vision), Pembelajaran Mesin (Machine Learning), dan Pembelajaran Mendalam (Deep Learning). Kami menggunakan rangka kerja dan platform industri terkini seperti TensorFlow, PyTorch, Hugging Face, dan OpenAI API untuk membina model AI yang tepat, boleh dipercayai, dan berskala. Setiap model AI yang kami bangunkan melalui proses latihan, pengesahan, dan pengujian yang ketat menggunakan data sebenar perniagaan anda bagi memastikan ketepatan ramalan yang tinggi.</p><p>Dalam bidang automasi proses, kami mereka bentuk dan melaksanakan Robotic Process Automation (RPA) yang menghapuskan tugasan berulang dan memakan masa. Daripada pemprosesan invois automatik, pengesahan data, penjanaan laporan, sehinggalah kepada aliran kerja kelulusan yang kompleks — automasi kami membebaskan tenaga kerja anda untuk memberi tumpuan kepada aktiviti bernilai tinggi yang memerlukan kreativiti dan pemikiran strategik manusia. Hasilnya, produktiviti meningkat secara mendadak sementara ralat manusia dikurangkan ke tahap minimum.</p><p>Kami juga menyediakan dashboard analitik pintar yang memaparkan cerapan (insights) perniagaan secara visual dan masa nyata. Dashboard ini menggabungkan data daripada pelbagai sumber, memprosesnya menggunakan algoritma AI, dan mempersembahkan hasil dalam bentuk carta, graf, dan indikator yang mudah difahami oleh pihak pengurusan. Dengan akses kepada data yang tepat dan terkini, anda boleh membuat keputusan berdasarkan bukti (data-driven decisions) dengan lebih yakin dan pantas.</p>',
                'content_en' => '<p>Artificial Intelligence (AI) and automation are no longer future technologies — they are current necessities for organizations seeking to remain competitive in increasingly fast-changing markets. We offer AI and automation solutions custom-tailored to your business needs, from intelligent customer service chatbots to complex predictive analytics systems that help make strategic decisions more accurately and quickly.</p><p>Our data science team possesses expertise across various AI domains including Natural Language Processing (NLP), Computer Vision, Machine Learning, and Deep Learning. We utilize the latest industry frameworks and platforms such as TensorFlow, PyTorch, Hugging Face, and OpenAI API to build AI models that are accurate, reliable, and scalable. Every AI model we develop undergoes rigorous training, validation, and testing processes using your actual business data to ensure high prediction accuracy.</p><p>In the field of process automation, we design and implement Robotic Process Automation (RPA) that eliminates repetitive and time-consuming tasks. From automated invoice processing, data validation, report generation, to complex approval workflows — our automation frees up your workforce to focus on high-value activities that require human creativity and strategic thinking. As a result, productivity increases dramatically while human errors are minimized.</p><p>We also provide intelligent analytics dashboards that display business insights visually and in real-time. These dashboards combine data from multiple sources, process it using AI algorithms, and present results in charts, graphs, and indicators that are easily understood by management. With access to accurate and up-to-date data, you can make evidence-based decisions with greater confidence and speed.</p>',
                'features' => ['NLP Processing', 'Machine Learning', 'Chatbot AI', 'Data Analytics'],
                'features_en' => ['NLP Processing', 'Machine Learning', 'Chatbot AI', 'Data Analytics'],
                'icon' => 'Cpu',
                'bg_path' => 'services/ai_bg.png',
                'order' => 4,
            ],
            [
                'name' => 'Pembangunan Aplikasi Mudah Alih',
                'name_en' => 'Mobile App Development',
                'description' => 'Aplikasi iOS dan Android yang responsif menggunakan Flutter atau React Native untuk pengalaman pengguna yang lancar.',
                'description_en' => 'Responsive iOS and Android apps using Flutter or React Native for smooth user experiences.',
                'content' => '<p>Dunia kini bergerak pantas ke arah mudah alih. Dengan lebih 80% trafik internet global datang daripada peranti mudah alih, memiliki aplikasi mobil yang berkualiti tinggi bukan lagi satu pilihan tetapi keperluan strategik. Kami membangunkan aplikasi mudah alih native dan cross-platform yang berprestasi tinggi, responsif, dan memberikan pengalaman pengguna yang luar biasa di kedua-dua platform iOS dan Android.</p><p>Kami menggunakan rangka kerja pembangunan terkini seperti Flutter dan React Native untuk pembangunan cross-platform, serta Swift dan Kotlin untuk pembangunan native. Pendekatan cross-platform membolehkan anda menjimatkan kos pembangunan sehingga 40% berbanding membangunkan dua aplikasi native secara berasingan, sambil mengekalkan prestasi dan rupa yang hampir setara dengan aplikasi native. Setiap aplikasi yang kami bangunkan dioptimumkan untuk pelbagai saiz skrin dan orientasi peranti, memastikan pengalaman yang konsisten tanpa mengira peranti yang digunakan oleh pengguna anda.</p><p>Kami mengintegrasikan ciri-ciri peranti terkini seperti push notifications, kamera, GPS/lokasi, sensor biometrik (Face ID, Touch ID), pembayaran dalam aplikasi, dan integrasi media sosial. Setiap aplikasi juga dilengkapi dengan keupayaan offline — membolehkan pengguna terus menggunakan aplikasi walaupun tanpa sambungan internet, dengan data disegerakkan secara automatik sebaik sahaja sambungan tersedia kembali. Ini amat penting untuk aplikasi yang digunakan dalam persekitaran lapangan atau kawasan dengan liputan rangkaian yang terhad.</p><p>Sebelum pelancaran, setiap aplikasi melalui proses jaminan kualiti (QA) yang ketat termasuk ujian fungsian, ujian prestasi, ujian keselamatan, dan ujian penerimaan pengguna (UAT). Kami juga menguruskan proses penerbitan ke Apple App Store dan Google Play Store, termasuk penyediaan metadata, tangkapan skrin, dan pematuhan kepada garis panduan kedai aplikasi masing-masing. Selepas pelancaran, kami menyediakan sokongan penyelenggaraan berterusan termasuk pembetulan pepijat, kemas kini versi OS, dan penambahbaikan ciri.</p>',
                'content_en' => '<p>The world is rapidly moving towards mobile. With over 80% of global internet traffic coming from mobile devices, having a high-quality mobile application is no longer an option but a strategic necessity. We develop high-performance, responsive native and cross-platform mobile applications that deliver exceptional user experiences on both iOS and Android platforms.</p><p>We utilize the latest development frameworks such as Flutter and React Native for cross-platform development, as well as Swift and Kotlin for native development. The cross-platform approach allows you to save up to 40% in development costs compared to building two separate native applications, while maintaining performance and appearance nearly equivalent to native apps. Every application we develop is optimized for various screen sizes and device orientations, ensuring a consistent experience regardless of which device your users are on.</p><p>We integrate the latest device capabilities such as push notifications, camera, GPS/location, biometric sensors (Face ID, Touch ID), in-app payments, and social media integrations. Every application is also equipped with offline capabilities — allowing users to continue using the app even without an internet connection, with data automatically synchronized once connectivity is restored. This is especially important for applications used in field environments or areas with limited network coverage.</p><p>Prior to launch, every application undergoes a rigorous quality assurance (QA) process including functional testing, performance testing, security testing, and user acceptance testing (UAT). We also manage the publishing process to Apple App Store and Google Play Store, including metadata preparation, screenshots, and compliance with respective app store guidelines. After launch, we provide ongoing maintenance support including bug fixes, OS version updates, and feature enhancements.</p>',
                'features' => ['Cross-platform', 'Push Notifications', 'Offline Support', 'App Store Publishing'],
                'features_en' => ['Cross-platform', 'Push Notifications', 'Offline Support', 'App Store Publishing'],
                'icon' => 'Smartphone',
                'bg_path' => 'services/mobile_bg.png',
                'order' => 5,
            ],
            [
                'name' => 'Keselamatan Siber',
                'name_en' => 'Cybersecurity',
                'description' => 'Perlindungan menyeluruh terhadap ancaman siber termasuk audit keselamatan dan pemantauan.',
                'description_en' => 'Comprehensive protection against cyber threats including security audits and monitoring.',
                'content' => '<p>Dalam landskap digital yang semakin kompleks, ancaman siber menjadi semakin canggih dan kerap. Serangan ransomware, kecurian data, pancingan data (phishing), dan serangan Distributed Denial of Service (DDoS) hanyalah sebahagian daripada risiko yang dihadapi oleh organisasi moden setiap hari. Kami menawarkan perkhidmatan keselamatan siber yang menyeluruh — daripada penilaian risiko dan audit keselamatan sehinggalah kepada pemantauan ancaman masa nyata dan tindak balas insiden pantas — untuk melindungi aset digital anda yang paling berharga.</p><p>Perkhidmatan kami bermula dengan Penilaian Risiko Keselamatan yang menyeluruh. Pasukan kami akan meneliti infrastruktur IT, aplikasi, rangkaian, dan polisi keselamatan sedia ada anda untuk mengenal pasti kelemahan (vulnerabilities) dan jurang keselamatan. Kami menggunakan alat pengimbasan kerentanan (vulnerability scanning) terkini serta metodologi ujian penembusan (penetration testing) yang mensimulasikan serangan dunia sebenar untuk menguji ketahanan sistem anda. Hasil penilaian ini dibentangkan dalam laporan terperinci berserta pelan tindakan pembetulan yang diutamakan mengikut tahap risiko.</p><p>Kami juga menyediakan perkhidmatan Pusat Operasi Keselamatan (SOC) yang memantau rangkaian dan sistem anda 24 jam sehari, 7 hari seminggu. Menggunakan teknologi Security Information and Event Management (SIEM) terkini, pasukan kami menganalisis berjuta-juta peristiwa keselamatan setiap hari untuk mengesan anomali dan potensi ancaman sebelum ia boleh menyebabkan kerosakan. Apabila insiden dikesan, protokol tindak balas pantas kami diaktifkan serta-merta — mengasingkan sistem terjejas, membendung ancaman, dan memulihkan operasi normal dalam masa yang paling singkat.</p><p>Selain perlindungan teknikal, kami juga menawarkan program latihan kesedaran keselamatan siber untuk kakitangan anda. Kajian menunjukkan bahawa lebih 90% pelanggaran keselamatan berpunca daripada kesilapan manusia. Program latihan kami merangkumi simulasi pancingan data, amalan kata laluan selamat, pengendalian data sensitif, dan prosedur pelaporan insiden — memperkasakan setiap ahli organisasi anda untuk menjadi barisan pertahanan pertama terhadap ancaman siber.</p>',
                'content_en' => '<p>In an increasingly complex digital landscape, cyber threats are becoming more sophisticated and frequent. Ransomware attacks, data theft, phishing, and Distributed Denial of Service (DDoS) attacks are just some of the risks modern organizations face daily. We offer comprehensive cybersecurity services — from risk assessment and security audits to real-time threat monitoring and rapid incident response — to protect your most valuable digital assets.</p><p>Our services begin with a comprehensive Security Risk Assessment. Our team will examine your existing IT infrastructure, applications, networks, and security policies to identify vulnerabilities and security gaps. We use the latest vulnerability scanning tools and penetration testing methodologies that simulate real-world attacks to test your system resilience. The results are presented in a detailed report with a prioritized remediation action plan based on risk levels.</p><p>We also provide Security Operations Center (SOC) services that monitor your networks and systems 24 hours a day, 7 days a week. Using the latest Security Information and Event Management (SIEM) technology, our team analyzes millions of security events daily to detect anomalies and potential threats before they can cause damage. When an incident is detected, our rapid response protocol is activated immediately — isolating affected systems, containing threats, and restoring normal operations in the shortest possible time.</p><p>Beyond technical protection, we also offer cybersecurity awareness training programs for your staff. Studies show that over 90% of security breaches originate from human error. Our training program includes phishing simulations, secure password practices, sensitive data handling, and incident reporting procedures — empowering every member of your organization to become the first line of defense against cyber threats.</p>',
                'features' => ['Security Audit', 'Penetration Testing', 'SSL Certificate', '24/7 Monitoring'],
                'features_en' => ['Security Audit', 'Penetration Testing', 'SSL Certificate', '24/7 Monitoring'],
                'icon' => 'Lock',
                'bg_path' => 'services/security_bg.png',
                'order' => 6,
            ],
        ];

        foreach ($services as $data) {
            $bgPath = $data['bg_path'];
            unset($data['bg_path']);

            $filename = basename($bgPath);
            
            // Create or reuse Media entry for the background image
            $media = Media::where('path', $bgPath)->first();
            if (!$media) {
                $media = Media::create([
                    'uuid' => (string) Str::uuid(),
                    'filename' => $filename,
                    'original_filename' => $filename,
                    'path' => $bgPath,
                    'disk' => 'public',
                    'type' => 'image',
                    'extension' => 'png',
                    'collection' => 'services',
                ]);
            }

            $data['featured_media_id'] = $media->id;
            $data['slug'] = Str::slug($data['name']);
            $data['is_active'] = true;

            Service::updateOrCreate(
                ['slug' => $data['slug']],
                $data
            );
        }
    }
}
